[package]
name = "toasty-driver-sqlite"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty-core.workspace = true
toasty-sql.workspace = true
rusqlite.workspace = true
url.workspace = true
uuid.workspace = true

# TODO: get rid of
serde.workspace = true
serde_json.workspace = true
