version = 1
next_migration_number = 2

[[migrations]]
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"

[[migrations]]
name = "0002_migration.sql"
snapshot_name = "0002_snapshot.toml"

[[migrations]]
name = "0003_migration.sql"
snapshot_name = "0003_snapshot.toml"

[[migrations]]
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
name = "0001_migration.sql"
snapshot_name = "0001_snapshot.toml"
