[package]
name = "toasty-sqlite"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
toasty-core.workspace = true
url.workspace = true

# TODO: get rid of
serde.workspace = true
serde_json.workspace = true
