[package]
name = "example-scratch"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty = { path = "../../src/toasty" }
toasty-sqlite = { path = "../../src/db/sqlite" }

tokio = { version = "1.18", features = ["full"] }
