[package]
name = "toasty-cli"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
toasty.workspace = true
toasty-core = { workspace = true, features = ["serde"] }

anyhow.workspace = true
clap.workspace = true
serde.workspace = true
toml.workspace = true
