[package]
name = "toasty-driver-dynamodb"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
toasty-core.workspace = true
aws-config.workspace = true
aws-sdk-dynamodb.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true
